
name: Update GitHub Profile Language Summary

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language-summary.yml"

permissions:
  contents: write

jobs:
  update-language-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: hexsyro
          BRANCH_NAME: main
          AUTO_PUSH: true
          EXCLUDE: ""
